version: '3.7'
services:
  ipmi_exporter:
    build:
      context: .
    command: "--config.file=/config.yaml"
    volumes:
      - ./ipmi_remote.yaml:/config.yaml:ro    # replace with your own config
    ports:
      - 9290:9290                           # bind on 0.0.0.0
      # - 127.0.0.1:9290:9290               # or bind to specific interface
    hostname: ipmi_exporter_docker
